#!/bin/bash



# ----------get the data file for the demo data and bake it in-------------
#git clone https://github.com/kynnemall/superviolin.git
#mv superviolin/superviolin/superviolin/res .
# ABOVE TWO LINES COULD WORK TOO BUT MIGHT AS WELL JUST GET CSV ONLY
curl -OL https://raw.githubusercontent.com/kynnemall/superviolin/master/superviolin/superviolin/res/demo_data.csv
mkdir example_data
mv demo_data.csv example_data/.




# ----------move `superviolin` to root -------------
# so can use `%run superviolin` in a notebook instead of needing `%run ./srv/conda/envs/notebook/bin/superviolin demo`
cp /srv/conda/envs/notebook/bin/superviolin ~/.
# NOTE
# just putting a symbolic link to it in path (see earlier version below) didn't allow using `%run` to work. And in fact it was already there before
# I even did that because `!superviolin --help` worked in notebooks without any `postBuild` file at all!!


#WHAT I ORIGINALLY TRIED THAT FAILED IN UNCOMMENTED FORM
# ----------to create a folder that is in the PATH -------------
#mkdir -p ~/.local/bin

# add simple symbolic link to superviolin in path like in 
# https://github.com/aborruso/bashnotebook/blob/0de5d657de745fffe53ed1acc35d01c75d389b6e/binder/postBuild#L48
# so can use `%run superviolin` in a notebook instead of needing `%run ./srv/conda/envs/notebook/bin/superviolin demo`
#cd ~/.local/bin
#ln -s ./srv/conda/envs/notebook/bin/superviolin superviolin
#cd ~